### ISSUE TITLE
[FEAT] 닉네임, 프로필 변경 스크린

### ISSUE THREAD

**Issue by halfmoon-mind** [gdsc-ssu/garbage-collector-client#15]
## **Description** *설명*
마이페이지처럼, 닉네임 혹은 프로필을 변경할 수 있는 기능

## **TODO** *해야할 일*
- [ ] 닉네임 변경 스크린 구현
- [ ] 프로필 변경 스크린 구현
- [ ] 백엔드와 API 통신 연결
