### ISSUE TITLE
[FIX] 랭크 스크린 로딩 불가

### ISSUE THREAD

**Issue by halfmoon-mind** [gdsc-ssu/garbage-collector-client#18]
## **Description** *설명*
- 랭크 스크린에서 모든 스크린이 불러와지지 않는 것으로 발견
- FutureBuilder 내부 data가 오류나는 경우에 대한 분기로 발견되어 수정 예정

## **TODO** *해야할 일*
- [x] Ranker 객체에 nickname이 null인 경우에 분기 처리
- [x] DB 조회 후 nickname이 null인 유저 update
- [x] 백엔드 파트에게 처리 요청
